// Single shared Base44 client for the dashboard SPA.
// App ID comes from .env (VITE_BASE44_APP_ID) — see SETUP.md.
//
// Typed SDK: base44/.types/types.d.ts (generated by `base44 types generate`)
// augments @base44/sdk's EntityTypeRegistry, so base44.entities.<Name> is fully
// typed. The reference directive below wires those declarations into this module.
/// <reference path="../../base44/.types/types.d.ts" />
import { createClient } from "@base44/sdk";

/** @typedef {import("../../base44/.types/types").Decision} Decision */

export const base44 = createClient({
  appId: import.meta.env.VITE_BASE44_APP_ID,
});

/** Auth gate helper: resolves the current user or redirects to Base44 login. */
export async function requireUser() {
  try {
    const user = await base44.auth.me();
    if (user?.email) return user;
  } catch {
    /* not logged in */
  }
  base44.auth.redirectToLogin(window.location.href);
  return null;
}

/**
 * Example of the generated typed SDK in real use: a space's active decisions,
 * newest first. The return type flows from the generated `Decision` interface —
 * no hand-written shape, and `entities.Decision` is typed via the registry.
 * @param {string} spaceId
 * @returns {Promise<Decision[]>}
 */
export function listDecisions(spaceId) {
  return base44.entities.Decision.filter({ space_id: spaceId, status: "active" }, "-decided_at");
}
