// Auto-generated by Base44 CLI - DO NOT EDIT
// Regenerate with: base44 types generate

export interface Commitment {
  space_id: string;
  /**
   * Display name of the person who owes this
   */
  who_name: string;
  who_tg_id?: string;
  what: string;
  due_at?: string;
  status?: "open" | "done" | "overdue";
  confidence?: number;
  source_msg_ids?: string[];
  last_nudged_at?: string;
  member_emails?: string[];
}

export interface Decision {
  space_id: string;
  /**
   * Short statement of what was decided
   */
  title: string;
  detail?: string;
  status?: "active" | "superseded";
  /**
   * Decision id that replaced this one
   */
  superseded_by?: string;
  confidence?: number;
  /**
   * Provenance: Telegram message ids this was extracted from
   */
  source_msg_ids?: string[];
  decided_at?: string;
  member_emails?: string[];
}

export interface Digest {
  space_id: string;
  period_start?: string;
  period_end?: string;
  /**
   * LLM-written narrative digest of the week
   */
  content_md?: string;
  stats?: {
    [k: string]: unknown | undefined;
  };
  cover_image_url?: string;
  emailed_to?: string[];
  member_emails?: string[];
}

export interface Event {
  space_id: string;
  title: string;
  starts_at?: string;
  location?: string;
  attendees?: string[];
  confidence?: number;
  source_msg_ids?: string[];
  member_emails?: string[];
}

export interface Expense {
  space_id: string;
  payer_name?: string;
  amount: number;
  currency?: string;
  description?: string;
  /**
   * Itemized lines when extracted from a receipt photo (ExtractDataFromUploadedFile)
   */
  items?: {
    label?: string;
    price?: number;
  }[];
  split?: {
    name?: string;
    share?: number;
  }[];
  /**
   * Private storage URI; dashboard fetches a signed URL on demand
   */
  receipt_file_uri?: string;
  source_msg_ids?: string[];
  member_emails?: string[];
}

export interface Membership {
  space_id: string;
  /**
   * Dashboard login email
   */
  user_email: string;
  /**
   * Telegram user id, linked when the member runs /link in the group
   */
  tg_user_id?: string;
  tg_display_name?: string;
  role?: "owner" | "member";
  /**
   * RLS mirror of the parent space's member list
   */
  member_emails?: string[];
}

export interface Question {
  space_id: string;
  text: string;
  asked_by?: string;
  status?: "open" | "answered";
  answer?: string;
  answered_via?: "human" | "agent" | "research";
  /**
   * URLs when answered via internet research
   */
  sources?: string[];
  source_msg_ids?: string[];
  member_emails?: string[];
}

export interface RawMessage {
  space_id: string;
  /**
   * Telegram update id — idempotency/dedup key (Telegram retries webhooks)
   */
  tg_update_id?: string;
  tg_message_id: string;
  sender_tg_id?: string;
  sender_name?: string;
  text?: string;
  media_type?: "photo" | "document" | "voice" | "none";
  /**
   * Telegram file_id for lazy download by ingest-media
   */
  tg_file_id?: string;
  /**
   * Base44 private-storage URI after ingestion
   */
  media_file_uri?: string;
  sent_at: string;
  processed?: boolean;
  member_emails?: string[];
}

export interface Space {
  /**
   * Display name of the space (usually the Telegram group title)
   */
  name: string;
  /**
   * Telegram chat id this space is bound to (unique)
   */
  tg_chat_id: string;
  tg_chat_title?: string;
  /**
   * One-time code posted by the bot to claim this space from the dashboard
   */
  invite_code?: string;
  /**
   * Dashboard users who may read this space. Denormalized onto all child records for RLS.
   */
  member_emails?: string[];
  /**
   * AI-generated weekly group portrait (GenerateImage)
   */
  cover_image_url?: string;
  timezone?: string;
  /**
   * Rolling counters: messages_seen, decisions, commitments, ...
   */
  stats?: {
    [k: string]: unknown | undefined;
  };
}

declare module '@base44/sdk' {
  interface EntityTypeRegistry {
    "Commitment": Commitment;
    "Decision": Decision;
    "Digest": Digest;
    "Event": Event;
    "Expense": Expense;
    "Membership": Membership;
    "Question": Question;
    "RawMessage": RawMessage;
    "Space": Space;
  }
  
  interface FunctionNameRegistry {
    "ask": true;
    "ingest-media": true;
    "mark-done": true;
    "bind-space": true;
    "nudge-commitments": true;
    "research": true;
    "process-messages": true;
    "telegram-webhook": true;
    "weekly-digest": true;
    "seed-demo": true;
  }
  
  interface AgentNameRegistry {
    "librarian": true;
  }
}